trigger:
    - main
    
    pool:
      name: local
    strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
