trigger: main # Disable CI triggers.
environment: ubuntu
strategy:                 # deployment strategy
  runOnce:              # default strategy
    deploy:
      steps:
      - script: echo Hello world
