jobs:
  # track deployments on the environment
- deployment: ubuntu
  environment: 'ubuntu'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
